version: '2'

services:

  central:
    build: ./backend/.
    environment:
      - SERVER=true
      - API_PORT=3000
      - JAEGER_SERVICE_NAME=central_server
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    depends_on:
      - jaeger

  bob:
    build: ./backend/.
    ports:
      - 3001:3000
    environment:
      - API_PORT=3000
      - P2P_PORT=4000
      - SERVER_ADDRESS=central:3000
      - JAEGER_SERVICE_NAME=bob
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    depends_on:
      - jaeger

  alice:
    build: ./backend/.
    ports:
      - 3002:3000
    environment:
      - API_PORT=3000
      - P2P_PORT=4000
      - SERVER_ADDRESS=central:3000
      - JAEGER_SERVICE_NAME=alice
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
