version: '2'

services:

  central:
    build: ./backend/.
    environment:
      - SERVER=true
      - API_PORT=3000

  client1:
    build: ./backend/.
    ports:
      - 3001:3000
    environment:
      - API_PORT=3000
      - P2P_PORT=4000

  client2:
    build: ./backend/.
    ports:
      - 3002:3000
    environment:
      - API_PORT=3000
      - P2P_PORT=4000


